name: "Project Build"

on: [pull_request]

env:
 NETCORE_VERSION: '6.0.x'

jobs:
 build:
  name: Build
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  
  - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
    uses: actions/setup-dotnet@v1
    with:
     dotnet-version: ${{ env.NETCORE_VERSION }}

  - name: Restore
    run: dotnet restore

  - name: Build
    run: dotnet build --no-restore -c Release
    
  - name: Test
    run: dotnet test --no-restore --verbosity normal
